### ISSUE TITLE
`:Iris` just hangs on "Selecting folder..."

### ISSUE THREAD

**Issue by jsatk** [soywod/iris.vim#33]
I'm a long time mutt user. Set up Iris to give it a whirl. Filled out all the settings following the `README.md`. But now it just hangs. Simply saying `Iris: Selecting folder...`. But I see no way to select a folder? I've read through the `README` several times and a few of the issues here but see no one else with this problem.

Is it possible it's hung downloading all the email for the first time?

Where does it store the mail? I could check if I knew...

**Comment by soywod** [comment]
Could you check the log file `/tmp/iris-api.log`? `Selecting folder...` appears straight after a folder is selected (if it's your first opening then it should be `INBOX` by default). So if it's stuck here it means the python api didn't send any reply yet. What is your vim version / python version / OS?

**Comment by soywod** [comment]
> Is it possible it's hung downloading all the email for the first time?

I don't think so, because I fetch emails by chunk, there is no cache (yet).

**Comment by soywod** [comment]
Also, when you type `:messages` in vim after `:Iris`, do you see the line `Iris: logged in!`? If not, then it could be an authentication issue.

**Comment by jsatk** [comment]
Hm. I just tried it in regular vim rather than neovim and it instantly says `Iris: job: connection lost`. :(

**Comment by jsatk** [comment]
There were no iris logs in `/tmp` and there are no Iris messages when I run `:messages`.

**Comment by soywod** [comment]
Hm. Strange that nothing works at all. It must miss sth. Please fill this form so we can debug properly:

- OS: 
- Neovim version:
- Vim version (the one used the triggers `connection lost`):
- The result of `:echo has('python3')`:
- What happens if you start manually the api? (go to `iris.vim` root folder and try `python3 api.py` or `./api.py`):

**Comment by jsatk** [comment]
macOS Catalina 10.15.5 (19F101)
---
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
---
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun  2 2020 16:45:43)
macOS version
Included patches: 1-850
---
`:echo has('python3')` returns `1`.
---
Running `python3 api.py` from `iris.vim` folder in `~/.vim/plugged`. `./api.py` gives the exact same result.
```
[I] ➜  iris.vim git:(master) python3 api.py
Traceback (most recent call last):
  File "api.py", line 19, in <module>
    from imapclient.imapclient import IMAPClient
  File "/Users/jesse.atkinson/.vim/plugged/iris.vim/imapclient/imapclient/__init__.py", line 10, in <module>
    from .imapclient import *
  File "/Users/jesse.atkinson/.vim/plugged/iris.vim/imapclient/imapclient/imapclient.py", line 19, in <module>
    from six import moves, iteritems, text_type, integer_types, PY3, binary_type, iterbytes
ModuleNotFoundError: No module named 'six'
```

**Comment by jsatk** [comment]
Thanks for your help @soywod!

**Comment by soywod** [comment]
> `ModuleNotFoundError: No module named 'six'`

Here is your problem. It seems that you miss a dependency from `imapclient`, I have no idea how the hell this can happen. Which tool do you use to install your plugins? I would suggest to reinstall the plugin (or at least to reinstall the submodule `imapclient` inside `iris.vim`'s plugin folder). If still not working, try to install manually this python dependency (`pip3 install --user six` or `pip install --user six`). Let me know.

**Comment by jsatk** [comment]
@soywod I use Plug. I just did a full uninstall & re-install. I saw it quickly clone the submodule. I manually installed `six` via `pip3 install --user six`. 

Same error in vim. But when I try to manually run it via `python3 ./api.py` I get this new error.

```
Traceback (most recent call last):
  File "api.py", line 21, in <module>
    logging.basicConfig(filename="/tmp/iris-api.log", format="[%(asctime)s] %(message)s", level=logging.INFO, datefmt="%Y-%m-%d %H:%M:%S")
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1898, in basicConfig
    h = FileHandler(filename, mode)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1087, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1116, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/tmp/iris-api.log'
```

Any idea how I can allow Iris to be able to write to `/tmp`?

**Comment by jsatk** [comment]
I promise I don't have anything unique or weird in my set up. I just `:PlugInstall`-ed it 😆

**Comment by soywod** [comment]
So it seems that `six` needs to be install manually. Maybe it's related to MacOS. I will update the doc. For the other error I will change the log folder, I let you know. Thank you for your help, now we now what's going on :)

**Comment by jsatk** [comment]
@soywod I did install it manually. It's still not working due to:

```
Traceback (most recent call last):
  File "api.py", line 21, in <module>
    logging.basicConfig(filename="/tmp/iris-api.log", format="[%(asctime)s] %(message)s", level=logging.INFO, datefmt="%Y-%m-%d %H:%M:%S")
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1898, in basicConfig
    h = FileHandler(filename, mode)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1087, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1116, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/tmp/iris-api.log'```

**Comment by soywod** [comment]
I know, that's why you don't have the `ModuleNotFoundError: No module named 'six'` anymore :) this one is fixed. I will take care of the next one ASAP.

**Comment by jsatk** [comment]
Excellent. 

Running `:Iris` in vim now I get the new fun error. 

```
Iris: api: 'command SELECT illegal in state NONAUTH, only allowed in states AUTH, SELECTED'
```

Thanks again for your assistance.

**Comment by soywod** [comment]
I move the logs file to the plugin root dir (https://github.com/soywod/iris.vim/commit/9cc6a3cb689863943b2b3bdb9c61e0bec8589c02), it should fix your problem. Let me know.

> Thanks again for your assistance.

Thank YOU for your patience, I feel ashamed you go through all is bugs ^^

**Comment by jsatk** [comment]
> I move the logs file to the plugin root dir ([9cc6a3c](https://github.com/soywod/iris.vim/commit/9cc6a3cb689863943b2b3bdb9c61e0bec8589c02)), it should fix your problem. Let me know.
> 
> > Thanks again for your assistance.
> 
> Thank YOU for your patience, I feel ashamed you go through all is bugs ^^

😆 All good. I've never really loved mutt. Just sorta used it for past 5 or so years. This looks like it has the potential to be a lot nicer.

**Comment by jsatk** [comment]
@soywod Unfortunately I'm still getting this error when I run `nvim +Iris`

`Iris: api: 'command SELECT illegal in state NONAUTH, only allowed in states AUTH, SELECTED'`

Running `python3 api.py` seems to just... hang.

**Comment by soywod** [comment]
> Running python3 api.py seems to just... hang.

Which is very good, it means the api works well. Could you check this time the log file and see what it says? Should be at the root folder of the plugin.

**Comment by soywod** [comment]
Great :) are you using gmail btw? I know there is some issue with passwords, a third app needs to be declared with a dedicated password.

**Comment by jsatk** [comment]
I use Fastmail. Got it working by entering a new app password. So I think attempting to use the app password that's gpg encrypted that I use in mutt isn't working. But yeah. Looks good now. 😄 .

Thank you.

**Comment by soywod** [comment]
Great :) feel free to contribute. The project is young still, many features miss. Feedbacks are welcomed to improve it!

**Comment by lygamac** [comment]
I'm having a similar issue. After running `:Iris`, the last message showed is `selecting folder...`.

`:message` gives:
```
Iris: logging in...
Iris: selecting folder...
```
I installed `six` manually, it was missing on mine too. But nothing changes, it still stops at `selecting folder` (except there's no error when running `api.py` directly and the api is working).

`iris-api.log` contains nothing.

Anyway to debug this? @soywod

**Comment by soywod** [comment]
> `iris-api.log` contains nothing.

What do you mean? Nothing important or nothing at all? If so then there is a problem with logging, you should have sth. Iris should show error at least (vim side or python side).

**Comment by lygamac** [comment]
> Nothing important or nothing at all?

Nothing at all, it's just an empty file.

> What you can do is to increase the log level in api.py and see

I set the log level to `notset` (should display everything), still nothing. Neither in Neovim, vim, or python.

With keyboard interrupting in `api.py`, the last call was always `request_raw = sys.stdin.readline()`. So I moved the `while True` line after `request_raw = sys.stdin.readline()`. And still, the last call is still `request_raw = sys.stdin.readline()`. Maybe this is the problem why it's hanging?

I'm going to test in another OS if it would work.

**Comment by lygamac** [comment]
Well, with my Arch Linux, it does logged in, without the need of installing `six`, but with an error:
```
Iris: logging in...
Iris: selecting folder...
Iris: logged in!
Iris: api: '''NoneType'' object has no attribute ''decode'''
```

**Comment by soywod** [comment]
> Seems the problem is only for Windows.

Yes could be, I didn't try on this OS. The project is still experimental !

> Iris: api: '''NoneType'' object has no attribute ''decode'''

Do you have by any chance a mail without subject in your list?

**Comment by lygamac** [comment]
> If so then there is a problem with logging

Just tested, the logging feature works just fine. I added `logging.error('test')` at the start and the this log shows as long as `logging.basicConfig` is removed (maybe there's something, but the error is showing now).

Now, when I use `python api.py`, something would be written into the log `[2020-11-10 21:42:18] test`. Nevertheless, using `:Iris` doesn't do this. I'm afraid that the `api.py` is not even executed.

> Do you have by any chance a mail without subject in your list?

I found one at (no subject) at 250. Iris only fetches the last 50 right?

**Comment by soywod** [comment]
> I found some (no subject) at 201-250. Iris only fetches the last 50 right?

Yes indeed, so maybe it's not this. Should be one of this call that fails:

![image](https://user-images.githubusercontent.com/10437171/98738170-96b6b900-23a7-11eb-87e6-479ac226cb92.png)

**Comment by lygamac** [comment]
I tried many values with `let g:iris_emails_chunk_size` it works. And there was a mail causing that problem.

It's a quite normal mail, when I sent or forwarded the same mail to myself, Iris can load properly. Strange (Deleting that I could fetch to 200+ mails, still stops for mails without subject though).


In the mean while I have also tried gmail, yahoo and hotmail(outlook) accounts. Both gmail and yahoo gave me `Iris: api: 'command SELECT illegal in state NONAUTH, only allowed in states AUTH, SELECTED'` just like others did (I don't have 2 step verification enabled, so specific passwords are not available for me). Outlook works, and my college's mail too. Is there something wrong?

I'll tried to see if I can fix the windows problem when I'm free.

**Comment by lygamac** [comment]
Problem: in `function! s:handle_data(data_raw)`, the data type passed is not login.

The function is called, but does not get in to the condition of `if data.type == "login"`.

**Comment by soywod** [comment]
> It's a quite normal mail, when I sent or forwarded the same mail to myself, Iris can load properly. Strange

Strange indeed. It could be interesting to compare the same mail before and after (the raw email with headers) to check the difference.

> In the mean while I have also tried gmail, yahoo and hotmail(outlook) accounts. Both gmail and yahoo gave me `Iris: api: 'command SELECT illegal in state NONAUTH, only allowed in states AUTH, SELECTED'`

This message means Iris can't connect to the IMAP server, it's as simple as "bad login". I know that you can't use your regular password with gmail, you need to register a [third party app](https://support.google.com/accounts/answer/3466521?hl=en) and use the password they will give you. For Yahoo should be sth similar?

> Problem: in `function! s:handle_data(data_raw)`, the data type passed is not login.

About the Windows problem? I think we start to have to many problems :smile: I invite you to split them into dedicated issues. I will close this one since it seems not to be the same problem.

**Comment by lygamac** [comment]
>  since it seems not to be the same problem

Yes, it seems not. I'll open them in another issue
